### ISSUE TITLE
Makefile does not output documentation

### ISSUE THREAD

**Issue by mholman5721** [UI-CS383-Group4/assign3#17]
Dear Group 4,

I have opened a new issue in the hopes that it emails all of you - my apologies if this is not right.

According to the assignment writeup, the makefile is meant to output documentation that we should submit. As of now, our program does not do this. Below, is some code forwarded by Prof. Bolden to Matthew Kirkland who then forwarded it to me. Supposedly, this will generate the output, but I don't know how that is to happen other than the latex:: latex stack.tex rule, which seems to only create a tex file called stack.tex. Unfortunately, I have not had the chance to test it yet. However, I believe it would be in our best interest to get the makefile to do the output that it needs to do.

Thanks,

Matthew Holman

#  Makefile
#    a makefile for the stack example.
#

#            SHELL = /bin/sh

#              TOP = .
#      CURRENT_DIR = .

#               CC = g++

#              CPP = /lib/cpp $(STD_CPP_DEFINES)
              CXX = g++

#          DESTDIR =

#        CCOPTIONS =
#           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(ALLDEFINES)
#           RM_CMD = $(RM) *.CKP *.ln *.o core errs ,* *~ *.a

#
#

SRCS= teststack.cpp \
stack.cpp \
link.cpp

OBJS= teststack.o \
stack.o \
link.o

teststack.o: stack.h

stack.o: stack.h \
link.h

link.o: link.h

PROGRAMS = testStack

all::  $(PROGRAMS)

#LOCAL_LIBRARIES = $(XLIB)

testStack: $(OBJS)
$(CXX) -o $@ $(OBJS)
#$(CXX) -o $@ $(OBJS) $(LDOPTIONS) $(LOCAL_LIBRARIES) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

clean::
$(RM) testStack 

latex::
latex stack.tex    

###########################################################################
# common rules for all Makefiles - do not edit

emptyrule::

clean::
rm *.o

**Comment by trevmo** [comment]
I think the solution to this is to add a latex rule to the makefile that compiles <filename>.tex. Then we will need to add a .gitignore file that targets *.tex. This will allow each of us to create our own .tex file in our local directories without them being pushed to the central repo. (Since we are supposed to author our own memos and do not want them tracked by git.)
